In [4]:
import numpy as np

A = np.array([[-2],[4],[5]])
B = np.array([[1,3,-6]])

print('A =\n',A)
print('B =\n',B)

#matrix multiplication
AB = A*B

AB_t = AB.T

print('Transpose of AB =\n',AB.T)
#printing LHS

A_t = A.T
B_t = np.array(B).reshape(-1,1)

print('Transpose A =\n',A_t)
print('Transpose B =\n',B_t)

#matrix multiplication 
B_tA_t = B_t*A_t

print('Transpose B*Transpose A =\n',B_tA_t)
#printing RHS
print('Therefore LHS = RHS')

A =
 [[-2]
 [ 4]
 [ 5]]
B =
 [[ 1  3 -6]]
Transpose of AB =
 [[ -2   4   5]
 [ -6  12  15]
 [ 12 -24 -30]]
Transpose A =
 [[-2  4  5]]
Transpose B =
 [[ 1]
 [ 3]
 [-6]]
Transpose B*Transpose A =
 [[ -2   4   5]
 [ -6  12  15]
 [ 12 -24 -30]]
Therefore LHS = RHS
